steps:
  # Step 1: Install pnpm@10.15.1
  - name: node:20
    id: 'install-pnpm'
    entrypoint: bash
    args:
      - -c
      - |
        npm install -g pnpm@10.15.1
        pnpm --version

  # Step 2: Install dependencies
  - name: node:20
    id: 'install-deps'
    entrypoint: bash
    args:
      - -c
      - |
        npm install -g pnpm@10.15.1
        pnpm install

  # Step 3: Build project
  - name: node:20
    id: 'build'
    entrypoint: bash
    args:
      - -c
      - |
        npm install -g pnpm@10.15.1
        pnpm build

  # Step 4: Run tests
  - name: node:20
    id: 'test'
    entrypoint: bash
    args:
      - -c
      - |
        npm install -g pnpm@10.15.1
        pnpm test

options:
  logging: CLOUD_LOGGING_ONLY
