options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'node:$_NODE_VERSION'
    entrypoint: npm
    args: ['i', '-g', 'pnpm@10.15.1']

  # Install dependencies
  - name: 'node:$_NODE_VERSION'
    entrypoint: pnpm
    args: ['install']

  # Run tests
  - name: 'node:$_NODE_VERSION'
    entrypoint: pnpm
    args: ['test']

# Set a longer timeout since NestJS builds can take a while
timeout: 1800s