options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Install dependencies
  - name: node:20
    entrypoint: npm
    args: ['ci']

  # Run tests
  - name: node:20
    entrypoint: npm
    args: ['test']

# Set a longer timeout since NestJS builds can take a while
timeout: 1800s