name: Pulumi

on:
  push:
    branches:
      - main

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      
      - name: check node version
        run: node -v
      
      - name: install pnpme
        run: npm i -g pnpm@10.15.1
      
      - name: install deps
        run: pnpm install
      
      - name: run build
        run: pnpm build
      
      - name: run tests
        run: pnpm test