name: Pulumi

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: my-terraform-project-471305
  REGION: asia-southeast1
  REPO_OWNER: thisdotchris
  REPO:  my-first-cloud-run-repo
  IMAGE: my-cloud-run-image
  SERVICE: my-cloud-run-service

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      
      - name: check node version
        run: node -v
      
      - name: install pnpm
        run: npm i -g pnpm@10.15.1
    
      - name: install deps
        run: pnpm install
    
      - name: install pulumi deps
        run: cd pulumi && pnpm install
        
      # - name: run build
      #   run: pnpm build
      
      # - name: run tests
      #   run: pnpm test

      # - name: Authenticate to Google Cloud
      #   uses: google-github-actions/auth@v2
      #   with:
      #     credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # - name: Configure Docker for Artifact Registry
      #   run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      # - name: Build Docker image
      #   run: |
      #     IMAGE_URI=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ github.sha }}
      #     echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
      #     docker build -t $IMAGE_URI .

      # - name: Push Docker image
      #   run: docker push ${{ env.IMAGE_URI }}

      - uses: pulumi/actions@v6
        with:
          work-dir: ./pulumi
          command: up
          stack-name: thisdotchris/dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          IMAGE_URI: ${{ env.IMAGE_URI }}
          PROJECT_ID: ${{ env.PROJECT_ID }}
          REGION: ${{ env.REGION }}
          REPO_OWNER: ${{ env.REPO_OWNER }}
          REPO: ${{ env.REPO }}
          IMAGE: ${{ env.IMAGE }}
          SERVICE: ${{ env.SERVICE }}